# Generated by Django 4.0.4 on 2022-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
