# Generated by Django 4.0.4 on 2022-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='news.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
