# Generated by Django 4.0.4 on 2022-05-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_author_name_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'text')},
        ),
    ]
