# Generated by Django 4.0.4 on 2022-05-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='chat_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
