# Generated by Django 4.0.4 on 2022-05-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_subscriber_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSendedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
